### PR TITLE
Dependency issue and infinite recursive render fix

### PR DESCRIPTION
**Pull request by chasebgale**
Also to answer your question in code about the date, it's using UTC time as the default for calculations, 8pm EST being 12am UTC/GMT

Sorry about missing our call last time, we can resched whenever you want

### CODE REVIEW

**Review by joe-millers-code — APPROVED** [review]

**Review by joe-millers-code — APPROVED** [review]
another hook added to my book of tricks. thank you sir

**Comment by joe-millers-code** [comment]
no worries about the call we can always make that happen whenever - the timezone thing seems so obvious now that you have told me lol.

**Review by joe-millers-code — COMMENTED** [review]
this simplified date render is also one of those things like the time zone where i feel stupid for seeing it hahahahah my prowess for digital magic has increased again. thank you, great wizard.

**Comment by chasebgale** [comment]
hahah no worries brother you are able to see what I am doing and pick up on it, killing it

**Pull request merged**
